###퀴즈 게시판 조회
GET http://localhost:8080/api/quizzes/recent
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzMxNTUxNjAzLCJleHAiOjE3MzE1NTUyMDN9.Tw3hE4ghgJZeOel2nP7f_eEv6HbCfnWhw2jXNq_U_dI

###퀴즈 등록
POST http://localhost:8080/api/courses/1/quizzes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzMxNTUxNjAzLCJleHAiOjE3MzE1NTUyMDN9.Tw3hE4ghgJZeOel2nP7f_eEv6HbCfnWhw2jXNq_U_dI
Content-Type: application/json

{
  "title": "퀴즈 제목",
  "question": "문제 내용",
  "choices": [
    "보기 1",
    "보기 2",
    "보기 3",
    "보기 4"
  ],
  "correctChoice": 2
}