###퀴즈 게시판 조회
GET http://localhost:8080/api/quizzes/recent
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzMxNDg1OTc2LCJleHAiOjE3MzE0ODk1NzZ9.Iizqo1KoRcZF7YZOyvshXfisHQPS62L6n-_EQOC9B6M