###랭킹 요청
GET http://localhost:8080/api/users/2/ranking
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzMxMzk5NTk4LCJleHAiOjE3MzE0MDMxOTh9.05FmLhjhScUNL-IfXaXQbk3KTXa21qwdSfPEeKK5owA