###랭킹 요청
GET http://localhost:8080/api/users/1/ranking
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzMxNDY0MDY5LCJleHAiOjE3MzE0Njc2Njl9.Ptf4H90dJby8J5Y1hDiPeRI1Ndgo6XbZ-_nEmHW_WMg