###아이템 전체 조회
GET http://localhost:8080/api/store/items
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzMxOTI0NjIyLCJleHAiOjE3MzE5MjgyMjJ9.P-alI0WQ58lp6shh7_SlZgu3Af08VaZ0-eg5NVRvPvw